name: focusflow
description: FocusFlow - Smart Study Planner for Students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Networking
  dio: ^5.4.3+1
  # Local storage
  shared_preferences: ^2.2.3
  # Google Fonts (Poppins)
  google_fonts: ^6.2.1
  # State management
  provider: ^6.1.2
  # Utils
  intl: ^0.20.2
  # Image picker (untuk foto profil)
  image_picker: ^1.1.2
  # Local notifications (reminder deadline)
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/